---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mutate-nginx
data:
  foobar: |
    {"patch": [{"op": "replace", "path": "/spec/containers/0/image", "value": "nginx:v1.19"}]}


---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    mutate.example.com/config: "mutate-nginx"
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
