---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mutate-nginx
data:
  foobar: |
    {"containers": [{"name": "foobar", "image": "alpine", "command": ["ash", "-c", "sleep 30"]}]}
  #  foobar: |
  #    {"patch": [{"op": "add", "path": "/spec/initContainers", "value": [{"name": "foobar", "image": "alpine", "command": ["ash", "-c", "sleep 5"]}]}]}


---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    mutate.example.com/config: "mutate-nginx"
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
